"use server";

import { createAdminClient } from "@/lib/supabase/admin";
import { getRegistrationPackageById } from "@/config/pricing";
import { getPaymentProvider } from "@/lib/payments/service";
import { simulateMockOutcome } from "@/lib/payments/mock";
import { sendEmail } from "@/lib/email/service";
import { registrationSchema, type RegistrationInput } from "@/lib/validation/registration";

export interface CreateRegistrationResult {
  ok: true;
  registrationId: string;
  registrationDbId: string;
  orderId: string;
  checkout: Record<string, string>;
  amount: number;
}

export interface CreateRegistrationError {
  ok: false;
  error: string;
}

/**
 * Creates a registration + payment intent in one step. The server is the
 * only source of truth for the amount charged — it is looked up from the
 * active registration package, never trusted from the client — and the
 * registration ID is generated by the database, never by client code.
 */
export async function createRegistration(
  input: RegistrationInput
): Promise<CreateRegistrationResult | CreateRegistrationError> {
  const parsed = registrationSchema.safeParse(input);
  if (!parsed.success) {
    return { ok: false, error: parsed.error.issues[0]?.message ?? "Invalid registration details." };
  }
  const data = parsed.data;

  const pkg = getRegistrationPackageById(data.packageId);
  if (!pkg) {
    return { ok: false, error: "Selected package is no longer available. Please choose another." };
  }

  let supabase;
  try {
    supabase = createAdminClient();
  } catch {
    return {
      ok: false,
      error:
        "Registration storage is not configured yet (no Supabase project connected). This is expected in local development without credentials.",
    };
  }

  const { data: registration, error: insertError } = await supabase
    .from("registrations")
    .insert({
      full_name: data.fullName,
      age: data.age,
      gender: data.gender,
      email: data.email.toLowerCase(),
      phone: data.phone,
      institution: data.institution,
      state: data.state,
      city: data.city,
      committee_preference: data.committeePreference,
      mun_experience: data.hasMunExperience ? "Yes" : "No",
      mun_experience_detail: data.hasMunExperience ? data.munExperienceDetail || null : null,
      package_id: pkg.id,
      status: "PENDING",
    })
    .select("id, registration_id")
    .single();

  if (insertError || !registration) {
    const duplicate = insertError?.code === "23505";
    return {
      ok: false,
      error: duplicate
        ? "A registration with this email or phone number already exists."
        : "Could not create your registration. Please try again.",
    };
  }

  const provider = await getPaymentProvider();

  const payment = await provider.createPayment({
    registrationId: registration.registration_id,
    registrationDbId: registration.id,
    amount: pkg.price,
    currency: pkg.currency,
    customerName: data.fullName,
    customerEmail: data.email,
    customerPhone: data.phone,
  });

  await supabase.from("payments").insert({
    registration_id: registration.id,
    provider: provider.name,
    order_id: payment.orderId,
    amount: pkg.price,
    currency: pkg.currency,
    status: "PENDING",
  });

  return {
    ok: true,
    registrationId: registration.registration_id,
    registrationDbId: registration.id,
    orderId: payment.orderId,
    checkout: payment.checkout,
    amount: pkg.price,
  };
}

/**
 * Dev-only helper: lets the registration UI simulate a payment outcome
 * against the mock provider when no real gateway is configured. Has no
 * effect against real providers, which are confirmed via server-verified
 * callbacks/webhooks instead.
 */
export async function simulateMockPayment(orderId: string, outcome: "success" | "failure") {
  if (process.env.PAYMENT_PROVIDER && process.env.PAYMENT_PROVIDER !== "mock") return;
  simulateMockOutcome(orderId, outcome);
}

export interface FinalizeResult {
  ok: boolean;
  status: "PENDING" | "PAID" | "FAILED";
  registrationId?: string;
}

/**
 * Called after the client returns from checkout (or after simulating a mock
 * outcome). Re-verifies the payment server-side — the client's own claim of
 * success is never trusted — and updates the registration/payment records.
 */
export async function finalizeRegistrationPayment(
  registrationDbId: string,
  orderId: string,
  clientPaymentId?: string,
  clientSignature?: string
): Promise<FinalizeResult> {
  const provider = await getPaymentProvider();
  const supabase = createAdminClient();

  const result = await provider.verifyPayment({
    orderId,
    paymentId: clientPaymentId,
    signature: clientSignature,
  });

  await supabase
    .from("payments")
    .update({
      status: result.status,
      payment_id: result.paymentId ?? null,
      method: result.method ?? null,
      provider_reference: result.providerReference ?? null,
    })
    .eq("order_id", orderId);

  if (result.verified && result.status === "PAID") {
    const { data: reg } = await supabase
      .from("registrations")
      .update({ status: "PAID" })
      .eq("id", registrationDbId)
      .select("registration_id, email, full_name")
      .single();

    if (reg) {
      await sendEmail({
        to: reg.email,
        subject: `GMUN 5.0 · Registration Confirmed (${reg.registration_id})`,
        html: `<p>Hi ${reg.full_name},</p><p>Your GMUN 5.0 registration <strong>${reg.registration_id}</strong> is confirmed. Payment received.</p>`,
      });
    }

    return { ok: true, status: "PAID", registrationId: reg?.registration_id };
  }

  return { ok: false, status: result.status === "PENDING" ? "PENDING" : "FAILED" };
}
